# Generated by Django 2.0.5 on 2018-05-31 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField()),
                ('today', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
